project:
  type: website

website:
  title: "Koda86 Blog"
  site-url: https://koda86.github.io
  description: "Posts on statistics, biomechanics, and other topics."
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/koda86/koda86.github.io
  page-footer:
    left: "© 2025 Koda86"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    code-fold: true
    code-tools: true
    highlight-style: github

execute:
  freeze: auto

