{
  "hash": "b5a55e4762fe70800adbfe8aa8a864e8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"When confidence intervals stop meaning what you think they mean\"\nauthor: \"Daniel Koska\"\ndate: 2026-01-03\ncategories: [confidence intervals, inference, visualization]\ndescription: \"On asymmetric confidence intervals and the limits of inference by eye\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\npage-layout: article\n---\n\n\n  \nEvery once in a while, I come across the same piece of statistical advice:\n\n> \"Don’t judge differences by whether confidence intervals overlap\".\n\nAt first glance, that sounds like one of those annoyingly technical rules statisticians like to repeat without explaining properly. For a long time, I more or less accepted it, but never really sat down to work through why it is true, when it matters, and what exactly goes wrong. This post is my attempt to do that.\n\n<!-- And, at least for normally distributed means, it’s largely settled science. -->\n\n### Asymmetric confidence intervals are everywhere\n\nConfidence intervals are often asymmetric. This is not some strange edge case. It is completely routine. Think of:\n\n- odds ratios\n\n- hazard ratios\n\n- rate ratios\n\n- quantiles\n\n- bootstrap(d) intervals\n\n- profile-likelihood intervals\n\nThese intervals are often perfectly fine. They are computed correctly, reported correctly, and for a single estimate they are usually interpreted correctly. In particular, asking whether such an interval includes the null value is often a perfectly sensible inferential step.\n\n### Where things quietly go off the rails\n\nWhether symmetric or not, the overlap between two separate confidence intervals is often used as a visual shortcut for deciding whether two effects differ. But that shortcut can easily disagree with the result of a corresponding statistical test.\n\nThe reason is simple: the statistical test does not ask whether two displayed intervals overlap. It asks whether the contrast between the two effects is compatible with zero on the relevant scale, for example whether $A - B = 0$, whether $\\log(A/B) = 0$, or, in a subgroup analysis, whether an interaction term is zero. That is a different inferential question from \"do the two displayed intervals overlap\"?\n\n<!-- Whether symmetric or not, the overlap between two separate confidence intervals is often examined visually as a shortcut for deciding whether two effects differ. Many times, the result of this shortcut is not compatible with the result of a corresponding statistical test. The statistical test asks whether the difference between the two effects is compatible with zero, for example whether $A - B = 0$, whether $\\log(A/B) = 0$, or, in a subgroup analysis, whether an interaction term is zero. That is a different inferential question from \"do the two displayed intervals overlap\"? -->\n\n<!-- In addition, the discrepancy described above (between the result of the visual examination and a test result) becomes worse with increasing asymmetry of confidence intervals. -->\n\n<!-- These intervals are often perfectly fine. They are computed correctly, reported correctly, and for a single estimate they are usually interpreted correctly. In particular, asking whether such an interval includes the null value is often a perfectly sensible inferential step. -->\n\n<!-- So the problem is not that asymmetric confidence intervals are invalid. The problem starts when we begin to compare them visually. -->\n\n<!-- ### Forest plots are usually not the problem -->\n\n<!-- A standard forest plot usually shows an estimate of a contrast — for example a treatment effect — together with its confidence interval. In that setting, checking whether the interval contains the null value is a perfectly legitimate inferential move. That remains true whether the interval is symmetric or asymmetric. So this is not an attack on forest plots. -->\n\nLet's have a closer look at this. Suppose a subgroup analysis reports something like this:\n\nSubgroup A: $\\mathrm{HR} = 0.72$ (95% CI 0.57–0.92)\n\nSubgroup B: $\\mathrm{HR} = 0.92$ (95% CI 0.64–1.31)\n\n$p_{\\text{interaction}} = 0.23$\n\nFormally, the message is straightforward: there is no convincing evidence that the treatment effect differs between subgroups. Visually, however, the message feels different. One interval excludes 1, the other does not. That creates a strong pull toward a different interpretation, something like:\n\n> “Looks like the treatment works in subgroup A, but not in subgroup B.”\n\nThat conclusion is very tempting. It is also not what the interaction test says. And this is where the trouble starts. The eye is informally comparing two separate confidence intervals, while the formal analysis is answering a different question.\n\n### The key mistake\n\nA confidence interval for effect A and a confidence interval for effect B are **not** the same thing as a confidence interval for the contrast between them. That contrast might be:\n\n- $A - B$,\n- $\\log(A/B)$,\n- or some other difference depending on the model and effect measure.\n\nThese are different inferential objects. And this is the real reason why CI overlap is unreliable. Even for symmetric 95% confidence intervals, overlap does not correspond neatly to a 5% test of equality. Once intervals are asymmetric on the displayed scale, the visual shortcut becomes even less trustworthy.\n\n### Why asymmetry makes the problem worse\n\nTo be clear: asymmetry does **not** destroy inference. What it destroys is the comforting illusion that inference by eye is geometrically straightforward. Once intervals are asymmetric on the plotted scale, several things become harder to interpret visually:\n\n- the point estimate is no longer centered in the interval,\n- left and right distances no longer mean the same thing,\n- the apparent distance between intervals depends on the chosen scale,\n- and overlap is no longer tied to any simple testing rule.\n\nThat last point matters a lot.\n\nFor ratio measures such as odds ratios or hazard ratios, intervals are often constructed on the log scale and then back-transformed. On the log scale, the interval may be perfectly symmetric. On the original scale, it becomes asymmetric. So even the visual geometry depends on the parameterization. That alone should make us suspicious of the idea that overlap on the displayed scale has some stable inferential meaning. Usually, it does not.\n\n\n### A simple simulation\n\nTo make this more concrete, let us simulate a situation in which two subgroup-specific effects are estimated independently.\n\nI simulate two log-effects, as one might obtain from two subgroup analyses. On the log scale, standard Wald inference is straightforward. I then exponentiate the estimates and intervals to obtain ratio measures with asymmetric confidence intervals on the original scale.\n\nThe question is: how often do two 95% confidence intervals overlap on the ratio scale even though the formal test comparing the two log-effects is statistically significant?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\n\nset.seed(1)\n\nn_sim <- 20000\n\n# True effects on the log scale\nmu1 <- log(0.60)\nmu2 <- log(1.10)\n\n# Standard errors of the subgroup-specific log-effects\nse1 <- 0.17\nse2 <- 0.17\n\nsim <- tibble(\n  theta1 = rnorm(n_sim, mu1, se1),\n  theta2 = rnorm(n_sim, mu2, se2)\n) %>%\n  mutate(\n    est1 = exp(theta1),\n    est2 = exp(theta2),\n\n    l1 = exp(theta1 - 1.96 * se1),\n    u1 = exp(theta1 + 1.96 * se1),\n    l2 = exp(theta2 - 1.96 * se2),\n    u2 = exp(theta2 + 1.96 * se2),\n\n    overlap = pmax(l1, l2) <= pmin(u1, u2),\n\n    z_diff = (theta1 - theta2) / sqrt(se1^2 + se2^2),\n    p_diff = 2 * pnorm(-abs(z_diff)),\n    sig_diff = p_diff < 0.05\n  )\n\nsummary_table_num <- sim %>%\n  summarise(\n    `Intervals overlap` = mean(overlap),\n    `Formal comparison is significant` = mean(sig_diff),\n    `Overlap despite significant difference` = mean(overlap & sig_diff),\n    `Overlap among significant comparisons` = mean(overlap & sig_diff) / mean(sig_diff)\n  )\n\nsummary_table <- summary_table_num %>%\n  mutate(across(everything(), ~ paste0(round(100 * .x, 1), \"%\")))\n\nkable(summary_table, align = \"cccc\")\n```\n\n::: {.cell-output-display}\n\n\n| Intervals overlap | Formal comparison is significant | Overlap despite significant difference | Overlap among significant comparisons |\n|:-----------------:|:--------------------------------:|:--------------------------------------:|:-------------------------------------:|\n|       59.7%       |              71.1%               |                 30.9%                  |                 43.4%                 |\n\n\n:::\n:::\n\n\n\nThe key result in Table 1 is **Overlap despite significant difference**. Here, it is 30.9%. So in nearly one third of all simulated datasets, the two asymmetric confidence intervals overlap even though the formal test indicates a statistically significant difference between effects.\n\nThat is not a small technical exception. It means that visual overlap can easily coexist with formal evidence for a difference, so \"the intervals overlap\" is clearly not a reliable shorthand for \"there is no difference\".\n\nThe final column, **Overlap among significant comparisons**, shows the same issue from another angle. Although the formal comparison is significant in 71.1% of simulations, 43.4% of those significant cases still display overlapping confidence intervals. Put differently, even when the data support a difference statistically, the visual impression from the two separate intervals is often ambiguous or misleading.\n\n### One plotted example\n\nWe can also extract one concrete simulation run where this happens and plot it.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexample_row <- sim %>%\n  filter(overlap, sig_diff) %>%\n  slice(1)\n\nexample_plot_data <- tibble(\n  subgroup = c(\"A\", \"B\"),\n  estimate = c(example_row$est1, example_row$est2),\n  lower = c(example_row$l1, example_row$l2),\n  upper = c(example_row$u1, example_row$u2)\n) %>%\n  mutate(across(-subgroup, ~ round(.x, 3)))\n\nexample_p <- example_row$p_diff[[1]]\n\nknitr::kable(\n  example_plot_data,\n  align = c(\"c\", \"c\", \"c\", \"c\"),\n  caption = \"One simulated example with overlapping asymmetric confidence intervals despite a statistically significant difference test.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: One simulated example with overlapping asymmetric confidence intervals despite a statistically significant difference test.\n\n| subgroup | estimate | lower | upper |\n|:--------:|:--------:|:-----:|:-----:|\n|    A     |  0.619   | 0.444 | 0.864 |\n|    B     |  1.147   | 0.822 | 1.600 |\n\n\n:::\n\n```{.r .cell-code}\nggplot(example_plot_data, aes(x = estimate, y = subgroup)) +\n  geom_point(size = 2.8) +\n  geom_errorbar(\n    aes(xmin = lower, xmax = upper),\n    orientation = \"y\",\n    width = 0.12\n  ) +\n  geom_vline(xintercept = 1, linetype = 2) +\n  labs(\n    x = \"Effect estimate (ratio scale)\",\n    y = NULL,\n    title = \"Overlapping asymmetric confidence intervals\",\n    subtitle = paste0(\n      \"But the formal test comparing effects gives p = \",\n      formatC(example_p, digits = 3, format = \"f\")\n    )\n  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](2026-03-01-overlapping_confidence_intervals_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nThe table presents one concrete simulated dataset in which the two subgroup-specific confidence intervals overlap, even though the formal test comparing the effects is statistically significant. So while confidence intervals can often be interpreted against their null value, they generally should not be interpreted against each other by eye.\n\nThat is true in general and it becomes especially important when the intervals are asymmetric on the displayed scale. The more asymmetric the displayed intervals become, the easier it is to forget that the visual comparison is happening on a scale whose geometry may have little to do with the inferential question we actually care about.\n\n### What to do instead\n\nIf the real scientific question is whether two effects are differ, then the right response is not to stare harder at two separate confidence intervals. Instead, compute one of the following:\n\n- a confidence interval for the difference in effects,\n- a confidence interval for the ratio of effects,\n- or an explicit interaction test.\n\nIn other words: answer the question you actually care about with the inferential object that actually corresponds to it.\n\nAsymmetric confidence intervals do not break inference. But they do break the intuition that visual overlap is telling us something simple. And that is exactly why they deserve a bit more caution than they usually get.",
    "supporting": [
      "2026-03-01-overlapping_confidence_intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}